"""
Canonical column names and detection-method labels for the bond table.

Why this file exists:
  Every other module imports from here. If you ever rename a column
  ("distance_A" → "Fe_N_distance_A"), you change ONE line here and the
  whole project follows. This is much safer than searching for strings.

Beginner notes:
  - Constants are written in UPPER_CASE by convention in Python.
  - `Enum` lets you list a small fixed set of named values (like a dropdown
    of allowed strings). Code that takes an Enum can never be passed a typo.
"""

from __future__ import annotations
from enum import Enum


# --- Bond table column names ----------------------------------------------
COL_CIF_FILE          = "cif_file"
COL_STRUCTURE_ID      = "structure_id"
COL_TEMPERATURE       = "temperature_K"
COL_FE_LABEL          = "Fe_label"
COL_N_LABEL           = "N_label"
COL_DISTANCE          = "distance_A"
COL_DISTANCE_ESD      = "distance_esd_A"
COL_DETECTION_METHOD  = "detection_method"
COL_SYMMETRY_RELATED  = "symmetry_related"
COL_WARNING           = "warning"

# Order matters — this is also the column order in the displayed table
# and in the exported CSV.
BOND_TABLE_COLUMNS: list[str] = [
    COL_CIF_FILE,
    COL_STRUCTURE_ID,
    COL_TEMPERATURE,
    COL_FE_LABEL,
    COL_N_LABEL,
    COL_DISTANCE,
    COL_DISTANCE_ESD,
    COL_DETECTION_METHOD,
    COL_SYMMETRY_RELATED,
    COL_WARNING,
]


# --- Detection method labels ----------------------------------------------
class DetectionMethod(str, Enum):
    """How a given Fe–N distance was found.

    Subclassing `str` means the enum members behave like strings, so they
    serialise nicely into pandas/CSV.
    """
    FORMAL_BOND          = "formal_bond"          # in mol.bonds (chemistry-based)
    GEOMETRIC_CANDIDATE  = "geometric_candidate"  # within cutoff but not a formal bond
    SYMMETRY_CONTACT     = "symmetry_contact"     # Fe–N pair generated by space-group symmetry
    UNKNOWN              = "unknown"              # fallback


# --- Reference bond-length bands (Å) for spin states ----------------------
# Widely-cited typical ranges from Halcrow's reviews.
# Used only as visual guides; the dashboard never uses them to label data.
SPIN_BANDS: dict[str, tuple[float, float]] = {
    "Fe(II) LS":  (1.95, 2.00),
    "Fe(II) HS":  (2.15, 2.25),
    "Fe(III) LS": (1.94, 2.00),
    "Fe(III) HS": (2.05, 2.15),
}


def select_bands(oxidation_state: str | None
                 ) -> dict[str, tuple[float, float]]:
    """Return the bands relevant to the given oxidation state.

    If `oxidation_state` is "Fe(II)" or "Fe(III)", returns just that
    oxidation state's LS + HS bands (clean, two non-overlapping
    annotations). Otherwise returns generalised LS / HS regions with
    a single label each — better than stacking four overlapping labels
    on the chart edge.
    """
    if oxidation_state == "Fe(II)":
        return {
            "Fe(II) LS": (1.95, 2.00),
            "Fe(II) HS": (2.15, 2.25),
        }
    if oxidation_state == "Fe(III)":
        return {
            "Fe(III) LS": (1.94, 2.00),
            "Fe(III) HS": (2.05, 2.15),
        }
    # Unknown / other: combined view.
    return {
        "LS region": (1.94, 2.00),
        "HS region": (2.05, 2.25),
    }


# --- Reference Σ (sigma) ranges by spin state -----------------------------
# Sources: Halcrow 2011, Ketkaew 2021 (OctaDist), and Halcrow & Murray
# tabulations of FeN6 SCO structures. These are typical ranges, not
# definitive cut-offs.
SIGMA_BANDS: dict[str, tuple[float, float]] = {
    "Fe(II) LS":  (30.0,  60.0),
    "Fe(II) HS":  (80.0, 140.0),
    "Fe(III) LS": (30.0,  70.0),
    "Fe(III) HS": (60.0, 100.0),
}


def select_sigma_bands(oxidation_state: str | None
                       ) -> dict[str, tuple[float, float]]:
    """Σ reference bands restricted to one oxidation state, or empty if
    not Fe(II)/Fe(III). The Σ reference chart is only meaningful for
    those two oxidation states."""
    if oxidation_state == "Fe(II)":
        return {
            "Fe(II) LS": SIGMA_BANDS["Fe(II) LS"],
            "Fe(II) HS": SIGMA_BANDS["Fe(II) HS"],
        }
    if oxidation_state == "Fe(III)":
        return {
            "Fe(III) LS": SIGMA_BANDS["Fe(III) LS"],
            "Fe(III) HS": SIGMA_BANDS["Fe(III) HS"],
        }
    return {}


def suggest_spin_state(mean_distance_A: float,
                       oxidation_state: str | None) -> str | None:
    """Empirical heuristic: LS / HS / borderline from a mean Fe–N distance.

    This is a SUGGESTION, never an assignment. It returns a short
    descriptive phrase the UI displays as a hint. Returns None if no
    sensible guess is possible (e.g. no oxidation state supplied).

    Rules of thumb (Halcrow, Goodwin, Garcia reviews):
      Fe(II):
        ≤ 2.02 Å  → low-spin (S = 0)
        ≥ 2.13 Å  → high-spin (S = 2)
        otherwise → spin equilibrium / borderline
      Fe(III):
        ≤ 2.00 Å  → low-spin (S = 1/2)
        ≥ 2.05 Å  → high-spin (S = 5/2)
        otherwise → borderline
    """
    if oxidation_state == "Fe(II)":
        if mean_distance_A <= 2.02:
            return "consistent with **low-spin** (Fe(II), S = 0)"
        if mean_distance_A >= 2.13:
            return "consistent with **high-spin** (Fe(II), S = 2)"
        return ("**borderline / spin-equilibrium** range — "
                "could be a mixed or partially crossed-over sample")
    if oxidation_state == "Fe(III)":
        if mean_distance_A <= 2.00:
            return "consistent with **low-spin** (Fe(III), S = 1/2)"
        if mean_distance_A >= 2.05:
            return "consistent with **high-spin** (Fe(III), S = 5/2)"
        return "**borderline** range"
    # Other oxidation states or unknown — no reliable rule of thumb.
    return None
